import com.android.build.api.artifact.SingleArtifact

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.rikka.refine)
}

android {
    namespace 'rikka.shizuku.shell'
    defaultConfig {
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
    }
    buildTypes {
        debug {
            multiDexEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles 'proguard-rules.pro'
        }
    }
    dependenciesInfo {
        includeInApk false
    }
    lint {
        checkReleaseBuilds false
    }
    buildFeatures {
        buildConfig = true
    }
}

androidComponents {
    onVariants(selector().all()) { variant ->
        def variantName = variant.name
        def capName = variantName.substring(0, 1).toUpperCase() + variantName.substring(1)
        def apkDir = variant.artifacts.get(SingleArtifact.APK.INSTANCE)
        def mappingFile = (variantName == "release")
                ? variant.artifacts.get(SingleArtifact.OBFUSCATION_MAPPING_FILE.INSTANCE)
                : null
        def dexOutDir = file("${rootProject.rootDir.path}/manager/src/main/assets")
        def mappingOutDir = new File(new File(rootDir, "out"), "mapping")
        def versionNameProvider = variant.outputs.first().versionName

        tasks.register("extractRish${capName}Dex") {
            dependsOn(tasks.matching { it.name == "assemble${capName}" })
            inputs.dir(apkDir)
            outputs.file(new File(dexOutDir, "rish_shizuku.dex"))
            doLast {
                def apkFile = apkDir.get().getAsFile().listFiles().find { it.name.endsWith(".apk") }
                def dexFile = zipTree(apkFile).matching { include 'classes*.dex' }.singleFile
                copy {
                    from dexFile
                    into dexOutDir
                    rename { "rish_shizuku.dex" }
                }
                if (mappingFile != null) {
                    copy {
                        from mappingFile.get().getAsFile()
                        into mappingOutDir
                        rename { "cmd-v${versionNameProvider.get()}.txt" }
                    }
                }
            }
        }
    }
}

dependencies {
    implementation libs.hidden.compat
    compileOnly libs.hidden.stub
}
