version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/common"
      - "/manager"
      - "/server"
      - "/shell"
      - "/starter"
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
