def keystoreFile = rootProject.file('keystore.properties')
def signingFile = rootProject.file('signing.properties')

if (keystoreFile.canRead()) {
    def ks = new Properties()
    keystoreFile.withInputStream { ks.load(it) }

    android.signingConfigs.sign.storeFile = rootProject.file(ks['storeFile'])
    android.signingConfigs.sign.storePassword = ks['storePassword']
    android.signingConfigs.sign.keyAlias = ks['keyAlias']
    android.signingConfigs.sign.keyPassword = ks['keyPassword']
} else if (signingFile.canRead()) {
    def props = new Properties()
    props.load(new FileInputStream(signingFile))

    if (props != null) {
        android.signingConfigs.sign.storeFile file(props['KEYSTORE_FILE'])
        android.signingConfigs.sign.storePassword props['KEYSTORE_PASSWORD']
        android.signingConfigs.sign.keyAlias props['KEYSTORE_ALIAS']
        android.signingConfigs.sign.keyPassword props['KEYSTORE_ALIAS_PASSWORD']
    }
} else {
    android.signingConfigs.sign.storeFile = android.signingConfigs.debug.storeFile
    android.signingConfigs.sign.storePassword = android.signingConfigs.debug.storePassword
    android.signingConfigs.sign.keyAlias = android.signingConfigs.debug.keyAlias
    android.signingConfigs.sign.keyPassword = android.signingConfigs.debug.keyPassword
}
